### ISSUE TITLE
Prohibit update operation until a cluster has `NO_OPERATION` state

### ISSUE THREAD

**Issue by ribaraka** [instaclustr/operator#654]
We need to prevent all updating operations until a cluster is in the "RUNNING" state and/or has "NO_OPERATION". 
For example, there can be an error when you try to resize a cluster and change some of the config fields at the same time

**Comment by worryg0d** [comment]
If we just add validation of the `status.state` and `status.currentClusterOperation` fields it will block any updating requests. Also, it will never change the values of those fields because the validating webhook will also block update and patch requests from the operator. 
As I see the only way to implement it is to add some field/annotation that will indicate that an update request is sent by the operator. Probably something like `metadata.resourceVersion`...
