### ISSUE TITLE
Test Redis cluster resource 

### ISSUE THREAD

**Issue by ribaraka** [instaclustr/operator#665]
We need to test all Redis spec fields, and settings, check their workability, create/update/delete operations, add/remove data centers, etc.

Create separate issues for all bugs found during the test process. If not, add your comment on what was tested and the results in this issue.

**Comment by worryg0d** [comment]
I've found the following issues:
* operator allows changing the name of the DC (!). This is very important to fix because if we change the name of the DC the operator allows changing the value of any field of the DC
* if we change the value of `masterNodes` to not allowed value (e.a. from 3 to 4) the operator allows it, but the Instaclustr API returns an error about the unsupported `masterNodes` count. However, if we want to change the value back the validating webhook doesn't allow us to `decrease the amount of master nodes`.
* when updating `nodesNumber` the API returns the following error: `status code: 500, message: {"errors":[{"message":"Null or invalid data encountered","name":"Unknown error"}]}`
* when updating `replicationFactor` it doesn't send API call
* when adding additional DC to the cluster with the private link enabled the operator allows changing the resource spec, but the API returns an error `multi datacentre is unsupported`. However, if we try to change it back the validating webhook denies an updating request
* the operator allows creating cluster with the `privateLink` enabled for the clusters with `AZURE_AZ` and `GC` cloud providers.

**Comment by ribaraka** [comment]
tested. all is working
